version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "maven"
    directory: "/hello-world-maven"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/hello-world-gradle"
    schedule:
      interval: "weekly"
