name: Java CI with Gradle

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "hello-world-maven/**"
      - "hello-world-war/**"
  pull_request:
    types:
      - opened
      - synchronize
    branches: [ master ]
    paths-ignore:
      - "hello-world-maven/**"
      - "hello-world-war/**"

  workflow_dispatch:

jobs:
  build:
    name: Build Gradle Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Cache the Gradle packages to speed up build
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0

      - name: Build and test project with Gradle
        run: |
          cd hello-world-gradle/
          chmod +x gradlew
          ./gradlew build

  release-jar:
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: git fetch --prune --unshallow

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config advice.addIgnoredFile false

      - name: Get the last tag
        id: last_tag
        run: |
          cd hello-world-gradle/
          chmod +x gradlew          
          LAST_TAG=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')
          echo "${LAST_TAG}"
          echo "::set-output name=last_tag::${LAST_TAG}"

      - name: Determine bump type
        id: bump_type
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:%s)
          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          if [[ "$COMMIT_MSG" == *"[major]"* ]]; then
            echo "::set-output name=bump_type::major"
          elif [[ "$COMMIT_MSG" == *"[minor]"* ]]; then
            echo "::set-output name=bump_type::minor"
          elif [[ "$COMMIT_MSG" == *"[patch]"* ]]; then
            echo "::set-output name=bump_type::patch"
          elif [[ "$COMMIT_MSG" == *"[hotfix]"* ]] || [[ "$COMMIT_MSG" == *"[bugfix]"* ]]; then
            echo "::set-output name=bump_type::patch"
          elif [[ "$BRANCH_NAME" == "feature/"* ]]; then
            echo "::set-output name=bump_type::minor"
          elif [[ "$BRANCH_NAME" == "bugfix/"* ]] || [[ "$BRANCH_NAME" == "hotfix/"* ]]; then
            echo "::set-output name=bump_type::patch"
          else
            echo "::set-output name=bump_type::build"
          fi

      - name: Calculate new version
        id: new_version
        run: |
          LAST_TAG=${{ steps.last_tag.outputs.last_tag }}
          echo "${LAST_TAG}"
          IFS='.' read -ra PARTS <<< "$LAST_TAG"
          MAJOR=${PARTS[0]}
          MINOR=${PARTS[1]}
          PATCH=${PARTS[2]}
          BUILD=${PARTS[3]}
          BUMP_TYPE=${{ steps.bump_type.outputs.bump_type }}

          if [ "$BUMP_TYPE" == "major" ]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
            BUILD=0
          elif [ "$BUMP_TYPE" == "minor" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
            BUILD=0
          elif [ "$BUMP_TYPE" == "patch" ]; then
            PATCH=$((PATCH + 1))
            BUILD=0
          else
            BUILD=$((BUILD + 1))
          fi

          NEW_VERSION="$MAJOR.$MINOR.$PATCH.$BUILD"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "::set-output name=new_version::${NEW_VERSION}"

      - name: Update Version in gradle properties file
        run: |
          cd hello-world-gradle/
          ./gradlew -Pversion="${NEW_VERSION}"

      - name: Build and test project with Gradle
        run: |
          cd hello-world-gradle/
          ./gradlew build

      - name: List gradle.properties Files
        run: |
          find . -maxdepth 3 -type f -name "gradle.properties" > gradle_properties_files.txt
          cat gradle_properties_files.txt

      - name: Add and Commit Gradle Properties Files
        run: |
          while IFS= read -r file; do
            git add "$file"
          done < gradle_properties_files.txt
          git commit -m "Add and commit gradle.properties files [skip ci]"

      - name: Push Changes
        run: |
          # Use the PAT secret to authenticate the push
          # git remote set-url origin "https://${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}.git"
          git push origin master  # Replace with the name of your protected branch

      - name: Tag and Create Release
        run: |
          NEW_VERSION=${{ steps.new_version.outputs.new_version }}
          git tag -a "$NEW_VERSION" -m "Release v$NEW_VERSION"
          git push origin $NEW_VERSION

      - name: Merge changes from master to develop
        run: |
          # Authenticate using a GitHub token
          #gh auth login --with-token  ${{ secrets.ACCESS_TOKEN }}

          # Ensure you're on the 'develop' branch
          git checkout develop

          # Fetch and merge the latest changes from the source branch
          git pull origin master -X ours

          # Push the merged changes to 'develop'
          git push origin develop
