name: Java CI with Gradle

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "hello-world-maven/**"
      - "hello-world-war/**"
  pull_request:
    types:
      - opened
      - synchronize
    branches: [ master ]
    paths-ignore:
      - "hello-world-maven/**"
      - "hello-world-war/**"

  workflow_dispatch:

jobs:
  build:
    name: Build Gradle Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Cache the Gradle packages to speed up build
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.0.0

      - name: Build and test project with Gradle
        run: |
          cd hello-world-gradle/
          chmod +x gradlew
          ./gradlew build

  release-jar:
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: git fetch --prune --unshallow

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.0.0

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config advice.addIgnoredFile false

      - name: Get the last tag
        id: last_tag
        run: |
          cd hello-world-gradle/
          chmod +x gradlew
          LAST_TAG=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')
          echo "${LAST_TAG}"
          echo "last_tag=${LAST_TAG}" >> $GITHUB_OUTPUT

      - name: Determine bump type
        id: bump_type
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:%s)
          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          if [[ "$COMMIT_MSG" == *"[major]"* ]]; then
            echo "bump_type=major" >> $GITHUB_OUTPUT
          elif [[ "$COMMIT_MSG" == *"[minor]"* ]]; then
            echo "bump_type=minor" >> $GITHUB_OUTPUT
          elif [[ "$COMMIT_MSG" == *"[patch]"* ]]; then
            echo "bump_type=patch" >> $GITHUB_OUTPUT
          elif [[ "$COMMIT_MSG" == *"[hotfix]"* ]] || [[ "$COMMIT_MSG" == *"[bugfix]"* ]]; then
            echo "bump_type=patch" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH_NAME" == "feature/"* ]]; then
            echo "bump_type=minor" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH_NAME" == "bugfix/"* ]] || [[ "$BRANCH_NAME" == "hotfix/"* ]]; then
            echo "bump_type=patch" >> $GITHUB_OUTPUT
          else
            echo "bump_type=build" >> $GITHUB_OUTPUT
          fi

      - name: Calculate new version
        id: new_version
        run: |
          LAST_TAG=${{ steps.last_tag.outputs.last_tag }}
          echo "${LAST_TAG}"
          IFS='.' read -ra PARTS <<< "$LAST_TAG"
          MAJOR=${PARTS[0]}
          MINOR=${PARTS[1]}
          PATCH=${PARTS[2]}
          BUILD=${PARTS[3]}
          BUMP_TYPE=${{ steps.bump_type.outputs.bump_type }}

          if [ "$BUMP_TYPE" == "major" ]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
            BUILD=0
          elif [ "$BUMP_TYPE" == "minor" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
            BUILD=0
          elif [ "$BUMP_TYPE" == "patch" ]; then
            PATCH=$((PATCH + 1))
            BUILD=0
          else
            BUILD=$((BUILD + 1))
          fi

          NEW_VERSION="$MAJOR.$MINOR.$PATCH.$BUILD"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT

      - name: Update Version in gradle properties file
        run: |
          cd hello-world-gradle/
          echo "$NEW_VERSION"
          ./gradlew -Dorg.gradle.project.version="${NEW_VERSION}"

      - name: Build and test project with Gradle
        run: |
          cd hello-world-gradle/
          ./gradlew build
