name: Java CI with Gradle

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "hello-world-maven/**"
      - "hello-world-war/**"
  pull_request:
    types:
      - opened
      - synchronize
    branches: [ master ]
    paths-ignore:
      - "hello-world-maven/**"
      - "hello-world-war/**"

  workflow_dispatch:

jobs:
  build:
    name: Build Gradle Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Cache the Gradle packages to speed up build
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0

      - name: Build and test project with Gradle
        run: |
          cd hello-world-gradle/
          chmod +x gradlew
          ./gradlew build
